version: "3.9"
services:
  kafka:
    image: docker.io/bitnami/kafka:3.5.0
    container_name: kafka-backend
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,AA:PLAINTEXT,BB:PLAINTEXT
      - KAFKA_CFG_LISTENERS=AA://:9092,BB://:9094,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=AA://0.0.0.0:9092,BB://0.0.0.0:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=AA
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /Users/ayush/kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: kafka-frontend
    ports:
      - "9000:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true

  # flowanalysis:
  #   image: analysis:v1
  #   container_name: flowanalysis-backend
  #   ports:
  #     - "5010:5010"


volumes:
  kafka_data:
    driver: local
